env_name: "MarLo-FindTheGoal-v0"
epochs: 5000
use_gae: True
algorithm: 'PPO'
num_processes: 2
num_test_episodes: 5
test_every_n_epochs: 1000 # No test for now
num_updates_per_epoch: 2
num_steps: 128
decreasing_lr: False
grayscale: True
skip_frame: 4
reward_scaling: 1
num_frame_stack: 4

algorithm_parameters:
  clip_param: 0.1
  ppo_epoch: 4
  num_mini_batch: 4
  value_loss_coef: 1
  entropy_coef: 0.01
  lr: 0.00025
  eps: 0.00001
  max_grad_norm: 0.5
  use_clipped_value_loss: 0.2